### ISSUE TITLE
Not working on Korean Client (English Language)

### ISSUE THREAD

**Issue by Shinzor** [zmilla93/SlimTrade#10]
Even tho I selected the right file " ...\Path of Exile\logs\KakaoClient.txt", it does not seem to recognize any messages received.

This is an example of how the file looks like inside:

2020/03/18 19:54:01 33356640 ac9 [INFO Client 6212] @From JajaBoba: Hi, I would like to buy your Ample Silver Flask of Heat listed for 1 chaos in Delirium (stash tab "~price 1 chaos"; position: left 2, top 2)
2020/03/18 19:54:14 33369421 ac9 [INFO Client 6212] : JajaBoba has joined the area.
2020/03/18 19:54:25 33381000 ac9 [INFO Client 6212] : Trade accepted.
2020/03/18 19:54:29 33384812 ac9 [INFO Client 6212] @From JajaBoba: gl

Anything that can be done?

Thank you for the good work! :)

**Comment by zmilla93** [comment]
It looks like @from (and presumably @to) are lowercase for you. These words are capitalized in the English client. Assuming this is correct and not some auto formatting by github, it is an easy fix. @to @To @From @from

[Here's a prerelease containing that fix.](https://github.com/zmilla93/SlimTrade/releases/tag/PRE-v0.2.4-krf) If these changes are correct, you can use the prerelease version until the fix is added in the next major patch.

**Comment by zmilla93** [comment]
Initially I thought from was lower case "from", but that is just from github formatting @[name] as a mention. The message has the exact same format as the English client and works in my test environment, so that isn't the issue.

Once the client path is set correctly, does the history load when you relaunch SlimTrade?

**Comment by Shinzor** [comment]
I double-checked and that is correct, the "from" has its initial capsed.
Yes, the history is working correctly... What else could it be? :(

**Comment by zmilla93** [comment]
The history is built by reading the Client.txt file at launch, so reading the file itself isn't the issue. Something likely goes wrong after launch. Have messages ever worked, or did they stop working at some point?

Make sure you are on the latest version (0.2.4) currently, as that does contain some small bug fixes for the chat parser.

[I've created a new issue explaining how to run SlimTrade from the command line.](https://github.com/zmilla93/SlimTrade/issues/11) If the problem persists, it would be great if you could try this and tell me if any errors appear. I'll also be expanding the debugging tools in the coming days to help make issues like this easier to test.

**Comment by Shinzor** [comment]
Yes, version is 0.2.4.
It never worked. :(
I've ran it from the powershell and admin powershell... no luck :(

**Comment by zmilla93** [comment]
Once it is running from powershell, wait until you send or receive a trade message, then check powershell again to see if any errors were printed out. You can also just send a trade message to yourself to test right away. My hope is that an error will appear sometime after launch.

I'll continue to think about this and browse over the code. Will also update when better debugging tools are added.

**Comment by Shinzor** [comment]
Been playing for more than 1hr on power shell, got many trade messages and transactions... Powershell says:

SlimTrade launched!
Launching chat parser...
Getting version list from github...
Running...                              v0.2.4
Latest Release...               v0.2.4

**Comment by zmilla93** [comment]
Well that makes it clear the chat parser is working at launch since it builds the history, and it isn't crashing while running since that would be logged for sure.

To clarify, you said only messages received. Does that mean outgoing trades work? There is option to disable certain features (Options > General > Toggle Features). Did you perhaps disable popups by accident?

**Comment by Shinzor** [comment]
Both outgoing and incoming are not working, basically, nothing seems to be working...?
The boxes are black (toggled, I guess) on the settings.
:(

**Comment by zmilla93** [comment]
Sorry about the slow response. Can you confirm this [**issue still happens on v0.2.7**+](https://github.com/zmilla93/SlimTrade/releases/latest)?

If it does, it would be awesome if you could run a few tests to debug for me. Please follow the instructions closely!

## Test 1
- Open your client.txt file, make note of the last few lines, then close the file.
- Run POE, wait for someone to talk in global, close POE.
- Open your client.txt file again and verify that the last few lines changed. This ensures SlimTrade is reading the same file that POE is updating.

**If the client.txt file is being updated, move on to Test 2.**

## Test 2
- [Download this test version of SlimTrade.](https://github.com/zmilla93/SlimTrade/releases/tag/PRE-v0.1.0)
- [Run it from the command line while running POE.](https://github.com/zmilla93/SlimTrade/wiki/Running-from-Command-Line)
- Wait for several messages to be sent in global chat.
- Close SlimTrade an report the output.

Ideally, the output of Test 2 should print the location of the client file that you set, quickly report that the parser is proccing, and report it is updating every time someone talks in global. Both messages will be silenced after 3 reports.

**[Here is an example of an ideal outcome for Test 2.](https://i.imgur.com/AMYsvcN.png)**

Please let me know how the tests go!

**Comment by CypherConjured** [comment]
So I noticed I was seeing this, and I'm not getting any lines in the client.txt log at all for people with korean usernames. 

That lead me to this thread https://www.reddit.com/r/pathofexile/comments/c93tvs/bug_important_korean_whispers_not_being_logged_in/

So NAB, unfortunately.
