### ISSUE TITLE
Opacity settings

### ISSUE THREAD

**Issue by rayz0101** [zmilla93/SlimTrade#12]
I would like to suggest the addition of opacity settings for the trade windows.

It's great that you've modernized a new version of trade overlay, but the lack of opacity filters makes the play experience a bit scuffed as you can't see your window once all the trades come in, especially if theres 3+ trades. The addition of opacity settings on a timer setting would free up the screen space to better deal with content when not actively on the window thus allowing players to react to the game far better.

**Comment by zmilla93** [comment]
I've seen this feature on other trade macros, but never used it myself. I assume the messages are opaque when they appear, then turn transparent after a set delay? I'd also imagine this is per message, so each message fades out separately?

I've had some drawing bugs when using transparent windows in the past, but assuming I can work those out I think this is a very solid idea.

**Comment by rayz0101** [comment]
Awesome! Its a real QoL booster as you rarely need the notification fully visible the whole time when you get a message and a life saver in HC so you don't get tapped by an off screen effect. GL man, I like what I see so far!

**Comment by zmilla93** [comment]
Added in v0.2.10, as well as the ability to collapse trade messages.
