### ISSUE TITLE
Custom Cheatsheets

### ISSUE THREAD

**Issue by ktzee** [zmilla93/SlimTrade#13]
**Describe the bug**
The betrayal.png contained in the jar is outdated. 

**To Reproduce**
1. Download latest release
2. Hit Betrayal hotkey
3. See error

**Additional context**
http://poesyn.xyz/syndicate

I like the idea of being able to pull images/cheat sheets in general, but I believe that this approach of packing it into the jar is in general harder to maintain and not everyone might understand that a jar is just an archive and therefore not know how to replace content within it.
I think a cleaner approach would be to reference an images folder (external to the jar) where users can put their own images to be pulled up. In this way one can create his own cheatsheet hotkeys and the maintainers do not need to keep the files up to date.

**Comment by zmilla93** [comment]
I agree outdated references are an issue. Future versions of SlimTrade will include an auto updater, so pushing out small bug fixes for things like this will be much more realistic. I also want to remake any references I use myself so they are easier to update. The current a version is one made by someone else that I quickly edited for league launch, and I'm not very knowledgeable of Betrayal myself.

I do like the idea of people being able to customize images. I think I'll still include defaults for things like betrayal to make things easy for people who don't care for that level of control, but allow it to be overridden, and completely new popups to be made.

**Comment by zmilla93** [comment]
Updated the betrayal image in 0.2.5. Custom cheat sheets will be added later.

**Comment by zmilla93** [comment]
Custom cheat sheets have been added in v0.2.10.
