### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by 4NightTerror** [zmilla93/SlimTrade#15]
1. Is it possible to add a hotkey to close incoming/outcoming trade message?
2. Is it possible to combine buttons "Thanks!" and leave party?

**Comment by zmilla93** [comment]
First one will almost certainly be added when the new macro system is implemented. [More info here.](https://github.com/zmilla93/SlimTrade/issues/6).

The second one I'm not sure if I'll add. While certainly possible, the solution would likely be to allow people to chain commands together, which is a layer of complexity I'd rather avoid. I'll consider it, but currently unsure if it will be added.

**Comment by zmilla93** [comment]
Added in v0.2.5.
