### ISSUE TITLE
Sound when entering hideout?

### ISSUE THREAD

**Issue by sjurado** [zmilla93/SlimTrade#17]
Is it possible to add a sound whenever someone else joins your hideout? Had this with trade companion. Sometimes people take a while to go to your hideout and since the party list is not visible while opening your stash, it's easy to miss the "XXXXXX has joined the area" message. A sound queue helps you realize your trade is already waiting.

Great work by the way. By far the best trading tool I've used so far.

**Comment by zmilla93** [comment]
I like this idea. Should be easy to add, just need to find another sound effect I like.

Glad you are liking the program!

**Comment by zmilla93** [comment]
Added in v0.2.5.
