### ISSUE TITLE
Does not capture trade messages in non-English characters

### ISSUE THREAD

**Issue by dennistlt** [zmilla93/SlimTrade#18]
**Describe the bug**
For outgoing messages, if the trade message is written in non-English characters (tested Korean and Russian), SlimTrade would not capture it including both the pop up and the trade history. 
Same with incoming messages. Doesn't capture if the the buyer has a non-English name.

**To Reproduce**
1. Go to poe trade site.
2. Click "Whisper" to copy a non-English trade message.
3. Send in poe client.
4. The trade message is not captured.
5. Open SlimTrade History.
6. The non-English trade is not captured in History.

**Setting** 
Operation System: Win7
Graphics Card: Nvidia GT750M
Language settings if not English: English
Keyboard settings if not QWERTY: QWERTY

**Screenshots**
If your issue is graphics related, consider including a screenshot.

**Additional context**

**Comment by zmilla93** [comment]
This is less of a bug and more just something I haven't implemented yet. I have to manually add any languages that I want to support, which is a bit tedious as I only speak English. That said, I'll try and get some basic support for the most common languages fairly soon, then expand support over time.

**Comment by zmilla93** [comment]
Added support for French, German, Korean, Portuguese, Russian, Spanish, and Thai trades in v0.2.5.

**Comment by dennistlt** [comment]
Thanks for the fantastic change!
