### ISSUE TITLE
Quick paste hotkey

### ISSUE THREAD

**Issue by 4NightTerror** [zmilla93/SlimTrade#19]
You can check not work 'Quick paste hotkey'.
Automatic works fine, but conlict with trade macro programms (ctrl+d).
Thanks.

**Comment by zmilla93** [comment]
Do you mean you have the same hotkey set in both SlimTrade and another program, and that it is causing issues? If that is the case I'll look into it, but there probably isn't a ton I can do. You should consider using different hotkeys.

**Comment by 4NightTerror** [comment]
Аny key on keyboard not work for quick paste hotkey.
Friend says he has the same problem.

**Comment by zmilla93** [comment]
Looks like I broke this while updating the hotkey system. Thanks for the report!

Fixed in v0.2.6 which I've just released.
