### ISSUE TITLE
Option to move the default icon location and trade window location

### ISSUE THREAD

**Issue by tfp** [zmilla93/SlimTrade#2]
I would highly appreciate if I could move the (even if tiny) icon to another place. The same with where trades will pop up.

**Comment by zmilla93** [comment]
This feature already exists. Options > General > Basics > Edit Overlay. I may have to add a prompt for this during the setup so people are made more aware of it.

Side note, there is a bug where the colors on the edit overlay window are not updated correctly, so it will be hard to read unless you are using the default Solarized Light theme. I've already fixed this, I just haven't released the patch for it quite yet.

**Comment by tfp** [comment]
Oh wow. Sorry, thought I really looked everywhere! Very good setting, only a little bit hard to find :)
