### ISSUE TITLE
Stash Highlighter not working (anymore)

### ISSUE THREAD

**Issue by Bonaf1de** [zmilla93/SlimTrade#25]
Stash Highlighter doesn't work anymore. I get the following warning message:

![Error - Item could not be parsed](https://user-images.githubusercontent.com/35174152/80566619-af571700-89f3-11ea-9c28-9975b452d77e.png)

SlimTrade v0.2.8
Operation System Win10 10.0.18362

Running the app from the command line doesn't reveal any error messages.

**Comment by zmilla93** [comment]
That error message is not produced by SlimTrade. I assume you have additional 3rd party tools installed?

Close all other POE tools and see if SlimTrade is working correctly. Then, open the additional tools one by one by until the error occurs again to find out which tool is causing the issue. Please let me know which program causes the issue, if it is a specific item or all items, and specify which part of the stash helper doesn't work.

Left clicking the stash helper to search the name in your stash will copy the item name to clipboard, simulate a CTRL + F key press to focus the search bar, then pastes the item name. It is certainly possible that that part of the macro could conflict with other 3rd party programs if they detect related key combos.

**Comment by Bonaf1de** [comment]
You were absolutely right!
It was POE Overlay, in which I had set a command via CTRL + F...

Thanks for your swift and extensive answer!
