### ISSUE TITLE
SlimTrade overlay not visible with new Vulcan renderer and Windowed Fullscreen

### ISSUE THREAD

**Issue by jordan-millard** [zmilla93/SlimTrade#28]
**Describe the bug**
SlimTrade overlay not visible with new Vulcan renderer

**Reproduce**
If easy to reproduce, describe the steps:
1. Go to options
2. In the Graphics tab go to the Renderer option
3. Select Vulkan (Beta) and also go to Windowed Fullscreen Mode option above.

**Setting** 
SlimTrade Version v0.2.9
Operation System Windows 10

**Additional context**
Other poe tool overlays have had this same issue and resolved it, though I think they had to add a setting option to clarify that you are using Vulcan.

This is how the developer of [poe-lurker](https://github.com/C1rdec/Poe-Lurker) added fullscreen-windowed support for vulkan in [this commit](https://github.com/C1rdec/Poe-Lurker/commit/9647afcca0be6ff508a76545971a30ace23f7a90)

The other workaround is to just use Fullscreen and alt+tab back and forth once and the overlay will be on top.

**Comment by zmilla93** [comment]
Thanks for the heads up. I'm intending to release one more update before league launch, so I'll have a look at the various solutions before then and either implement a fix, or add a link to one of the workarounds. Hopefully this will be fixed on GGG's end soon.

**Comment by zmilla93** [comment]
I've added instructions and a link to the AHK fix in both the readme and the patch notes for v.0.2.10.
