### ISSUE TITLE
Bigger UI scale

### ISSUE THREAD

**Issue by Razunter** [zmilla93/SlimTrade#29]
**What feature would you like added?**
UI scale 2x from current max

**Why do you want this feature added?**
I'm playing at high screen resolution and current UI is too small, hard to read, hard to click buttons.

-
THX for the app!

**Comment by zmilla93** [comment]
Currently the only part of the app that can easily be resized is the trade message window and button size (General > Basics > Edit Overlay Size & Location). At the very least I could increase the slider max for that in the sort term to make trades easier.

For the vast majority of the UI's buttons, text, sliders, etc the default sizes are used, so I'd have to add new functionality to all of the components to use a multiplie. Will take a bit longer to address properly, but it is something I can look into.

**Comment by zmilla93** [comment]
Font and icon size scaling has been added in v0.4.0, which will automatically scale UI components. Notification panel width can be scaled when editing the message overlay.
