### ISSUE TITLE
Auto Paste not wroking properly

### ISSUE THREAD

**Issue by stylerseb** [zmilla93/SlimTrade#30]
I have seen that there is a nother issue, with my exact same problem, but it is no longer activa as it seems, so I decide to write a new one.
Its pretty much the same thing, it works sometimes, but then its back to poe getting lit up on the taskbar, and nothing pasting.

I am running the latest version on windows 10.

I have tried restarting poe and slim trade and switching between the pasting modes, but nothing seems to fix the problem.

**Comment by stylerseb** [comment]
I forgot to mention that I also tried running it with the script mentioned on the other thread.

**Comment by zmilla93** [comment]
Now that I'm actually playing more, I've run into this issue myself quite a bit. I don't have a solution yet, but will be able to debug it much better now that I can actually reproduce it myself.

**Comment by zmilla93** [comment]
Fixed in v0.3.0. More technical response [here](https://github.com/zmilla93/SlimTrade/issues/23).
