### ISSUE TITLE
Mark more than one stash tab as quad

### ISSUE THREAD

**Issue by Kruschak** [zmilla93/SlimTrade#31]
I didn't find any info about the marking stash tabs as quad logic.

Is there a way like wildcards or part matching working like in the following example

I have the following stash tabs named like this:
~price 10 chaos 1
~price 10 chaos 2
~price 10 chaos 3

I would like to add a single rule to mark all stash tabs as quad with something like "~price".

Does this already exist and there is just no information about or would it be a new feature?

Best regards

**Comment by zmilla93** [comment]
Currently there is no functionality for that. I could do a wildcard system, but that might be a bit overkill. The simplest way would to be to add a drop down like ignore has to either match exactly or just check for containing phrases like "~price 10 chaos" in your example.

I do like the idea though, as it would be helpful for the start of new leagues.

**Comment by zmilla93** [comment]
Added an option to use "containing text" in v0.4.0.
