### ISSUE TITLE
two screens ?

### ISSUE THREAD

**Issue by kr0t3** [zmilla93/SlimTrade#32]
i cant use this software with two screens, only on main screen it shown,
When i try to move overlay it get stucked at the border of main screen.
What do i do?

**Comment by zmilla93** [comment]
When editing the overlay, you can right click the menubar or the message panel to toggle locking to the main monitor. Additionally, most windows will also lock to the main monitor when holding shift while moving them.

**Comment by kr0t3** [comment]
will try, ty.

**Comment by zmilla93** [comment]
Closing as I assume the solution worked.
