### ISSUE TITLE
Korean translations not working

### ISSUE THREAD

**Issue by khthe8th** [zmilla93/SlimTrade#33]
It seems the majority of the time SlimTrade doesn't pick up trade messages from players with non-english (specifically korean/chinese, seems okay with Russian) names. Occasionally it gets it, but most of the time (like this time I took a screenshot) it doesn't give the ding noise or show the overlay for what they have asked to purchase. 

https://i.imgur.com/oBKVjC3.jpg

**Comment by zmilla93** [comment]
_"Certain parts of Korea have legal restrictions preventing companies from logging the chat of users online. Their trade messages never appear in POE's client.txt file, so they cannot be parsed by SlimTrade. The issue can only be resolved on GGG's end."_

You can also verify this is whats happening by opening the game's client.txt file after receiving such a trade message and checking if the message was logged or not. If a message shows up in the client file but not SlimTrade it is a bug, but if it doesn't show up in the client file then there isn't much I can do without a fix from GGG.

**Comment by khthe8th** [comment]
Okay I will check next time I get an incoming message from one. I have the same problem on outgoing messages as well occasionally.

The below message was from my client.txt file but slimtrade did not pick it up as an outgoing trade message. i would imagine it's because it isn't in english? I use pathofexile.com/trade instead of poe.trade, and it auto translates

2020/07/02 10:36:15 1451683421 b5c [INFO Client 8196] @To NecTheo: 안녕하세요, 수확(보관함 탭 "~price 1 chaos", 위치: 왼쪽 6, 상단 11)에 1 chaos(으)로 올려놓은 독사의 미광 대형 스킬 군 주얼(을)를 구매하고 싶습니다

**Comment by khthe8th** [comment]
you are right, I got another incoming message from korean player that didn't show up, and it is also not in my client.txt

**Comment by zmilla93** [comment]
The outgoing messages are a proper bug. The program does support translations, but it is something I've had to do manually. It looks like with Korean I didn't handle the league name correctly, so it is hard coded to Delirium instead of being ambiguous. 

Good find. I'll get that fixed for the next patch, which will likely be sometime next week.

**Comment by zmilla93** [comment]
Sorry about the delay, got a bit busy. Fixed in v0.3.0.
