### ISSUE TITLE
Anyone having trouble with the installer? 

### ISSUE THREAD

**Issue by Booblord** [zmilla93/SlimTrade#34]
I click on the installer and nothing happens. Yes, I have java installed

**Comment by zmilla93** [comment]
First, try the steps in the first sections of the [troubleshooting guide](https://github.com/zmilla93/SlimTrade/wiki/Troubleshooting).

If that doesn't do anything, you can try [running from the command line](https://github.com/zmilla93/SlimTrade/wiki/Running-from-Command-Line) to see if it launches correctly, or if any errors are printed in the console.

**Comment by zmilla93** [comment]
Closed due to lack of information.
