### ISSUE TITLE
custom sounds

### ISSUE THREAD

**Issue by qLuxi** [zmilla93/SlimTrade#35]
I would like to have a function in the sound settings that allows me to assign my own sound files for specific actions.

**Comment by zmilla93** [comment]
It's really easy for me to add new sounds directly, so if you happen to have any royalty free sound effects, you can send them to me and I could add them for everyone. Adding a system for custom sounds is doable, but a fair bit more work and would require some changes to the audio system. I'll consider it.

If you really want, you could also modify the program directly. Right click slimtrade.jar and open it with 7zip/winrar to view the contents. Inside you'll see an audio folder with a bunch of .wav files. You can delete one of the files and replace it with your own, just use the same name as the file you deleted (including extension, so you'll need to use a .wav file). Just note that you'll have to redo this anytime there is an update, but that is usually only once a league right now.

For any programmers who want a method that allows for other extension types (requires maven), add audio files to the[ audio folder](https://github.com/zmilla93/SlimTrade/tree/master/src/main/resources/audio), then add new values to the [sound enum](https://github.com/zmilla93/SlimTrade/blob/master/src/main/java/com/slimtrade/core/audio/Sound.java) to reference the added files. Change `outputDirectory` in `pom.xml`, then recompile the program with `mvn clean compile assembly:single`.

**Comment by zmilla93** [comment]
The ability to add custom sound files has been added in v0.4.0.
