### ISSUE TITLE
How to move "Stash tab name window" in stash?

### ISSUE THREAD

**Issue by 59Nobless** [zmilla93/SlimTrade#36]
Can't use this. Beacause my trade tabs placed in folders. The grid can be adjusted by position, but the window with the "tab name" itself hides the folder names or tabs without folder.

![tabs](https://user-images.githubusercontent.com/77288101/104206525-719b0100-5451-11eb-9964-6a8623fe33ba.jpg)

How to move this window (Outlined in red)?
I would move it higher so it doesn't cover other folders and tabs.

**Comment by zmilla93** [comment]
I believe this issue is a result of the stash affinity update changing the stash UI. I'll look into getting it fixed before the new league on Friday.

**Comment by 59Nobless** [comment]
Sounds good. Thanks

**Comment by zmilla93** [comment]
A new toggle option has been added to increase this window's offset from the stash grid. _Options > General > Basics > Folder Offset_

Added in v0.3.1.
