### ISSUE TITLE
Visual glitch and slow responce 

### ISSUE THREAD

**Issue by Explaiz** [zmilla93/SlimTrade#37]
I remember this app was fast and really responsive, now I have like 500ms delay after pressing/aiming at buttons and also this visual glitch when you aim at literally anything on the interface https://imgur.com/a/7firtWd
i7-2600k/gtx770/16gb ddr3/latest win10/java updated;  if that matters

**Comment by zmilla93** [comment]
The visual glitch is a [known issue](https://github.com/zmilla93/SlimTrade/issues/5) that I unfortunately cannot reproduce myself and have not found a resolution for. I can only assume the slow responsiveness is a relic of that issue.
