### ISSUE TITLE
Hideout button

### ISSUE THREAD

**Issue by tstivers1990** [zmilla93/SlimTrade#40]
**What feature would you like added?**
I switched to this from MercuryTrade. I find it a better alternative to MercuryTrade. However, MercuryTrade had a constantly present overlay that provided a hideout button. I'd like to see something similar added to this, as I grew quite accustomed to it and think it's a great feature.

**Why do you want this feature added?**
This quickly allows you to access your hideout by clicking a button. There are quite a few hotkeys already and it can get cluttered. The less hotkeys I have, the better.

**Comment by zmilla93** [comment]
Added a hideout button to the menu bar in v0.4.0.
