### ISSUE TITLE
Allow moving overlays outside PoE bounds

### ISSUE THREAD

**Issue by tstivers1990** [zmilla93/SlimTrade#41]
**What feature would you like added?**
I'd like to be able to put overlays outside of the PoE window's bounds.

**Why do you want this feature added?**
I have multiple monitors and it would be better to put the overlay next to PoE on another monitor, rather than have it taking up valuable space in the PoE window itself.

**Comment by zmilla93** [comment]
Windows can be moved anywhere by default now. You can still snap windows to the edge of the monitor by holding shift. Works with multimonitor setups.
