### ISSUE TITLE
Incoming trades with characters that have Korean letters in their name

### ISSUE THREAD

**Issue by holyzeus** [zmilla93/SlimTrade#42]
**What feature would you like added?**
A way for SlimTrade to recognize trade requests with characters that use korean letters in their names.

**Why do you want this feature added?**
So trade messages by korean players don't just get discarded.

**Comment by zmilla93** [comment]
Certain parts of Korea have legal restrictions preventing companies from logging the chat of users online. Their trade messages never appear in POE's client.txt file, so they cannot be parsed by SlimTrade. The issue can only be resolved on GGG's end. If the message does appear in the client file but isn't detected by SlimTrade, feel free to reopen this issue.
