### ISSUE TITLE
Request: Allow Comma separated Character name list

### ISSUE THREAD

**Issue by Noshei** [zmilla93/SlimTrade#46]
**What feature would you like added?**
Allow the Character name filed to accept a comma separated list of character names.  Configure anything that uses the character name to loop through the names until one works then exit the loop.

**Why do you want this feature added?**
This would allow for slim trade to work across multiple characters at the same time without requiring that you change the name every time you change characters.

**Comment by arollyson** [comment]
If you're willing to make some HTTP requests, there might be a way to do this a little smarter by using the PoE website's get-characters route. You can grab a JSON array of a public account's characters from here like so: https://www.pathofexile.com/character-window/get-characters?accountName=mathil. There is a boolean called lastActive that gets set on every zone change (as far as I can tell) that you could use to find the current character.

```
{"name":"DeadeyeSelfCastGIGACHAD","league":"Archnemesis","classId":2,"ascendancyClass":2,"class":"Deadeye","level":94,"experience":2680024904,"lastActive":true}
```

**Comment by zmilla93** [comment]
Added a hotkey to change character in v0.4.0. Requires that your previous character still exist.
