### ISSUE TITLE
Weird quick paste behavior

### ISSUE THREAD

**Issue by dona3000** [zmilla93/SlimTrade#47]
**Describe the bug**
Need to press the quick paste key twice to send the message. Once will tab back into POE and then the second time will actually send the message. Rarely works in just one press and also sometimes requires 3 presses before the message is sent. Same issue if using second monitor to browse trade site. 

Tried automatic quick paste and on first try slimtrade started spamming the message really quick. Got kicked out of POE after 2 seconds and slimtrade crashed a few seconds later. That didnt happen again but using automatic I still need to click the whisper button several times before the message is actually sent.

Also possibly related I need to click the POE window twice before the overlay is actually displayed. So I need to click the window in the taskbar/alt tab to POE then click inside the POE window again before the overlay is actually displayed. Similarly when I tab OUT of the game the overlay stays displayed until I click somewhere in the new window.

**Reproduce**
If easy to reproduce, describe the steps:
Use quick paste feature

**Setting** 
SlimTrade Version 0.3.5
Operation System Win 10
*Graphics Card if visual bug*
*Language settings if not English*
qwerty English (United States) United States-International

**Screenshots**
If your issue is graphics related, consider including a screenshot.

**Command Line Errors**
Optionally, you can try running SlimTrade from the command line:
https://github.com/zmilla93/SlimTrade/wiki/Running-from-Command-Line
This will allow you to see any error messages while the program is running which can massively speed up the debugging process, although many bugs don't actually cause error messages.

**Additional context**

**Comment by dona3000** [comment]
Forgot to add that when I press my hotkey will in POE and while mousing over an item in my stash or inventory it will actually pick up the item and put it on the cursor (or put it back in stash/inventory if it is on the cursor). This only seems to be a thing with items so for example if I press my hotkey while mousing over my map device it will not click the map device.

**Comment by zmilla93** [comment]
Path of Exile had added this functionality to the game client, so this feature has been removed from SlimTrade in v0.4.0.
