### ISSUE TITLE
Null Pointer on Start

### ISSUE THREAD

**Issue by Shalwyn** [zmilla93/SlimTrade#49]
When i start SlimTrade from the Command Prompt got this Error:

> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
>         at com.slimtrade.core.utility.ChatParser.getTradeOffer(ChatParser.java:198)
>         at com.slimtrade.core.utility.ChatParser.init(ChatParser.java:60)
>         at com.slimtrade.App.launch(App.java:237)
>         at com.slimtrade.App.lambda$main$2(App.java:219)
>         at java.awt.event.InvocationEvent.dispatch(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.run(Unknown Source)
> SlimTrade Terminated

s1 has an idea?

**Comment by zmilla93** [comment]
I'll need to fix this properly on my end. For an easy fix on your end, close SlimTrade and POE, delete your Client.txt file, run POE, then run Slimtrade.

**Comment by zmilla93** [comment]
Fixed.
