### ISSUE TITLE
How do I run the program?

### ISSUE THREAD

**Issue by GracoKP** [zmilla93/SlimTrade#55]
Very basic question: this is the first time this has happened to me... But how do I run this application? I unzipped the "SlimTrade.jar" files in a folder on the desktop. In this folder I can't find any executable ???

How do I run the program?

https://github.com/zmilla93/SlimTrade/releases/tag/v0.3.5

**Comment by zmilla93** [comment]
Jar files can act like either zip files or executables. Double clicking on the jar file should run the program.

If the .jar file doesn't run when double clicked, then right click the jar file, open with, choose another app, and select Java Platform Binary. Check "Always use this app to open .jar files" to allow you to double click the file in the future.
