### ISSUE TITLE
Delay, crashing, only when tabbed into POE?

### ISSUE THREAD

**Issue by NeonStar-tv** [zmilla93/SlimTrade#58]
**Describe the bug**
Incredible delay while trying to use slimtrade

**Reproduce**
If easy to reproduce, describe the steps: 
Just using it normally. Honestly its kinda weird how flawless this was for leagues and now its just borked.

**Setting** 
SlimTrade Version 0.3.5
Operation System windows 11
2080ti

If your issue is graphics related, consider including a screenshot.
I have a video of me playing with it, please help me :)
https://www.twitch.tv/videos/1687456479

**Command Line Errors**
Optionally, you can try running SlimTrade from the command line:
https://github.com/zmilla93/SlimTrade/wiki/Running-from-Command-Line
This will allow you to see any error messages while the program is running which can massively speed up the debugging process, although many bugs don't actually cause error messages.

**Additional context**

**Comment by zmilla93** [comment]
Thanks for the report, and sorry for the delay! The app has had significant updates since this was posted that fixed many things. If you use a newer version and still have problems, feel free to open a new issue and I'll take a look.
