### ISSUE TITLE
Custom Sounds

### ISSUE THREAD

**Issue by 4lin** [zmilla93/SlimTrade#59]
**Custom Sounds**
Sound.java;

`
public enum Sound {

    PING1("Ping 1", "audio/ping1.wav"),
    PING2("Ping 2", "audio/ping2.wav"),
    BLIP1("Blip 1", "audio/blip1.wav"),
    BLIP2("Blip 2", "audio/blip2.wav"),
    BLIP3("Blip 3", "audio/blip3.wav"),
    JOIN1("Join 1", "audio/join1.wav"),
    TRADE1("Trade1", "audio/trade1.wav"),
    ;
`

**More personalized sounds**
Just to make this even more fun for everyone and be able to use personalized sounds when the player send message for trade i have the sound recorded saying "New trade request" and when the player is at your hideout another sound that i also have recorded saying "Player is here"
Here are the two wave sound files: [join_trade_wav.zip](https://github.com/zmilla93/SlimTrade/files/11185170/join_trade_wav.zip)

**Comment by zmilla93** [comment]
Support for custom sounds has been added in v0.4.0.
