### ISSUE TITLE
Chat key is configurable in PoE; non default breaks pasting

### ISSUE THREAD

**Issue by vitaminmoo** [zmilla93/SlimTrade#62]
**Describe the bug**
The key to open chat is configurable -  I've got mine bound to space.
This causes the features of PoeInterface.java that use `KeyEvent.VK_ENTER` to open the chat interface to fail.

**Reproduce**
1. Set chat key to space in PoE settings
2. Cause SlimTrade to try to send any message or do any command
3. Nothing happens

**Setting** 
SlimTrade Version: v0.3.5
Operation System: Windows 11

**Additional context**
The configured key is available in production_Config.ini in the ACTION_KEYS section as `chat` as the integer ascii character. It'd be pretty cool to parse it out so the user doesn't have to set it in SlimTrade.

Note that while the initial keycode changes to the setting in the config, sending the message remains as enter.

**Comment by zmilla93** [comment]
The ability to set the POE chat hotkey has been added in v0.4.5.

Support for individual keys has to be added manually due to converting mouse events between two different libraries. If you encounter an unsupported key, you'll see an error message you can report to have the key added.
