### ISSUE TITLE
Running as Administrator ?

### ISSUE THREAD

**Issue by rubenkruger** [zmilla93/SlimTrade#63]
How do you run this as administrator ?
My POE doesn't want to launch without me launching it as Admin, so this tool doesn't work if I run POE as Admin.

Any help appreciated.

**Comment by zmilla93** [comment]
I've added instructions on how to easily run SlimTrade as administrator to the [troubleshooting guide](https://github.com/zmilla93/SlimTrade/wiki/Troubleshooting).
