### ISSUE TITLE
Use the /leave command

### ISSUE THREAD

**Issue by Perry3D** [zmilla93/SlimTrade#66]
**What feature would you like added?**
The character name is no longer needed since the crucible league. Just use the `/leave` command to leave a party. See this video from GGG: https://www.youtube.com/watch?v=Q5IXQgag0LQ

**Why do you want this feature added?**
Changing characters would no longer require changing the name in the tool.

**Comment by zmilla93** [comment]
Ah nice, glad they finally added that. Will switch over to it in the next update.

**Comment by zmilla93** [comment]
Fixed in v0.4.1.
