### ISSUE TITLE
😍👌💕 Last Update 0.4.2 - Amazing hudge step.. I love it💕

### ISSUE THREAD

**Issue by serbalin** [zmilla93/SlimTrade#67]
**Great update 0.4.2**

I love it 💕 i hope you will continue maintaining this great app, respect!

**Comment by zmilla93** [comment]
Thanks for the kind words, glad you are enjoying the update!

Even if I reach the point where I no longer want to add new features, I plan to maintain the app with bug fixes and adapting to changes in the game.
