### ISSUE TITLE
Player joined area event not triggering

### ISSUE THREAD

**Issue by xuvvy** [zmilla93/SlimTrade#68]
**Describe the bug**
Custom WAV sounds can be added and play when tested in settings, but don't play or trigger when in-game. This was tested for Area Join.

**Reproduce**
If easy to reproduce, describe the steps:
1. Add a custom audio file (WAV) in the audio folder
2. Refresh the sound list
3. Add the custom sound to an action/trigger in the settings
4. The sound plays when tested inside the app, but seems to trigger never in-game

**Setting** 
SlimTrade Version: v0.4.3
Operation System: Windows 11
*Graphics Card if visual bug*
*Language settings if not English*
*Keyboard settings if not English/QWERTY*

**Screenshots**
![image](https://github.com/zmilla93/SlimTrade/assets/21984783/64cfbad5-49a9-42e3-9a6b-cd74da488191)

**Command Line Errors**
Optionally, you can try running SlimTrade from the command line:
https://github.com/zmilla93/SlimTrade/wiki/Running-from-Command-Line
This will allow you to see any error messages while the program is running which can massively speed up the debugging process, although many bugs don't actually cause error messages.

**Additional context**

**Comment by zmilla93** [comment]
Tested and working on my end. If sounds play in the settings, they should work anywhere since it uses the same code. You could try a custom sound on a different event to verify. I'm wondering if the player joined event isn't triggering.

What language is your client set to?

Players joining the area should also cause the player name, item name, and timer to change color. Does that part work? If not, you should open your client.txt, find the player joined area message, and post that here.

**Comment by xuvvy** [comment]
It seems like the area join is not properly being detected. Regardless of the sound being custom or not.

Here is a snippet from Client.txt
```
2024/04/11 00:16:46 50928218 ca3a50f6 [DEBUG Client 26184] Connect time to instance server was 32ms
2024/04/11 00:16:46 50928250 1186a061 [DEBUG Client 26184] Generating level 60 area "HideoutLibrary" with seed 1
2024/04/11 00:16:46 50928296 f22b6989 [INFO Client 26184] Tile hash: 1914648991
2024/04/11 00:16:46 50928296 f22b6988 [INFO Client 26184] Doodad hash: 0
2024/04/11 00:16:47 50929062 cff94598 [INFO Client 26184] : You have entered Enlightened Hideout.
2024/04/11 00:16:47 50929328 327589f0 [INFO Client 26184] [SHADER] Delay: ON
2024/04/11 00:20:39 51161281 cff94598 [INFO Client 26184] @From JoiningPlayerName: Hi, I would like to buy your Filled Coffin listed for 10 chaos in Necropolis (stash tab "Trade10c"; position: left 1, top 12)
2024/04/11 00:20:50 51171781 cff94598 [INFO Client 26184] @From JoiningPlayerName: all fracs
2024/04/11 00:21:01 51182468 cff94598 [INFO Client 26184] @To JoiningPlayerName: have 1 left
2024/04/11 00:21:02 51183828 cff94598 [INFO Client 26184] : JoiningPlayerName has joined the area.
2024/04/11 00:21:19 51200531 cff94598 [INFO Client 26184] : Trade cancelled.
2024/04/11 00:21:28 51209796 cff94598 [INFO Client 26184] : Trade accepted.
2024/04/11 00:21:36 51217734 cff94598 [INFO Client 26184] : TrickerST has joined the area.
2024/04/11 00:21:48 51229656 cff94598 [INFO Client 26184] : JoiningPlayerName has left the area.
2024/04/11 00:21:53 51234750 cff94598 [INFO Client 26184] : TrickerST has left the area.
```

I have just changed masked the player name in the Client.txt, otherwise the snippet above is unchanged. For the record, my language is English and I am also using Lailloken UI, which is the only other tool reading the Client.txt, but also doing so without issues.

**Comment by zmilla93** [comment]
I'm not quite sure why it's not triggering. Everything looks how it should.

I made a quick version that logs some stuff while trading. You should try running it, complete a trade, then send me the info from the log file (Options > Information > Logs Folder > Find the newest file).

https://github.com/zmilla93/SlimTrade/releases/tag/v0.4.4-pre1

A successful trade should look like this:

```
2024/04/10 18:49:56 | Handling trade message from "SmashyMcFireBalls".
2024/04/10 18:49:58 | Checking player joined "2023/12/09 20:55:35 403863171 cff94598 [INFO Client 3576] : SmashyMcFireBalls has joined the area.".
2024/04/10 18:49:58 | Handling player joined area for "SmashyMcFireBalls".
2024/04/10 18:49:58 | Comparing players "SmashyMcFireBalls" & "SmashyMcFireBalls" :: true
```

If you really don't want to post usernames publicly, you can send me the file in Discord if you prefer.

**Comment by xuvvy** [comment]
Client.txt snippet:
```
2024/04/11 11:04:47 1323000 37970285 [WARN Client 23232] Client couldn't execute a triggered action from the server.
action type id = 48518
2024/04/11 11:04:47 1323000 3796fae9 [WARN Client 23232] Instant/Triggered actionwas serialized to the client, but the client failed to execute the action.
skill_instance_id: 16386
action_id: 33825
object_id: 1050
target_id: 3527
flags: 129
2024/04/11 11:04:48 1323625 cff94598 [INFO Client 23232] : None shall stop you.
2024/04/11 11:04:50 1326328 cff94598 [INFO Client 23232] Sister Cassia: Oh!
2024/04/11 11:05:14 1350171 37970285 [WARN Client 23232] Client couldn't execute a triggered action from the server.
action type id = 58415
2024/04/11 11:05:14 1350171 3796fae9 [WARN Client 23232] Instant/Triggered actionwas serialized to the client, but the client failed to execute the action.
skill_instance_id: 16387
action_id: 33844
object_id: 1049
target_id: 4391
flags: 129
2024/04/11 11:06:24 1420015 cff94598 [INFO Client 23232] : Turn your world to ice.
2024/04/11 11:06:28 1424140 cff94598 [INFO Client 23232] Niko, Master of the Depths: Packed with energy, exile. Packed with energy.
2024/04/11 11:06:36 1432156 cff94598 [INFO Client 23232] : Open the eye of the storm.
2024/04/11 11:06:38 1434046 cff94598 [INFO Client 23232] Undertaker Arimor: Running out of room at the Necropolis...
2024/04/11 11:09:35 1611031 cff94598 [INFO Client 23232] @From 收手吧阿祖: Hi, I would like to buy your Breach Ring listed for 1 chaos in Necropolis (stash tab "~price 1 chaos"; position: left 3, top 3)
2024/04/11 11:09:45 1621078 88a9056d [DEBUG Client 23232] Got Instance Details from login server
2024/04/11 11:09:45 1621093 327589f0 [INFO Client 23232] [SHADER] Delay: OFF
2024/04/11 11:09:45 1621093 ca3a6a3d [INFO Client 23232] Connecting to instance server at 159.122.142.238:6112
2024/04/11 11:09:45 1621125 ca3a50f6 [DEBUG Client 23232] Connect time to instance server was 32ms
2024/04/11 11:09:45 1621156 1186a061 [DEBUG Client 23232] Generating level 60 area "HideoutLibrary" with seed 1
2024/04/11 11:09:45 1621218 f22b6989 [INFO Client 23232] Tile hash: 1914648991
2024/04/11 11:09:45 1621218 f22b6988 [INFO Client 23232] Doodad hash: 0
2024/04/11 11:09:46 1622109 cff94598 [INFO Client 23232] : You have entered Enlightened Hideout.
2024/04/11 11:09:47 1622812 327589f0 [INFO Client 23232] [SHADER] Delay: ON
2024/04/11 11:09:49 1624828 cff94598 [INFO Client 23232] : 收手吧阿祖 has joined the area.
2024/04/11 11:09:59 1635546 cff94598 [INFO Client 23232] @From 收手吧阿祖: ALL
2024/04/11 11:10:02 1637890 cff94598 [INFO Client 23232] : Trade cancelled.
2024/04/11 11:10:15 1651562 cff94598 [INFO Client 23232] : Trade cancelled.
2024/04/11 11:10:22 1658062 cff94598 [INFO Client 23232] @To 收手吧阿祖: got 5
2024/04/11 11:10:31 1667296 cff94598 [INFO Client 23232] : Trade accepted.
2024/04/11 11:10:35 1671296 cff94598 [INFO Client 23232] : 收手吧阿祖 has left the area.
2024/04/11 11:10:35 1671296 cff94598 [INFO Client 23232] @To 收手吧阿祖: Ty!
```

The relevant log file:
[log_2024-04-11_10h45m33s.txt](https://github.com/zmilla93/SlimTrade/files/14944033/log_2024-04-11_10h45m33s.txt)

**Comment by xuvvy** [comment]
Here is another example.

Client.txt
```
2024/04/11 12:15:24 5560468 ca3a50f6 [DEBUG Client 23232] Connect time to instance server was 32ms
2024/04/11 12:15:24 5560500 1186a061 [DEBUG Client 23232] Generating level 60 area "HideoutLibrary" with seed 1
2024/04/11 12:15:24 5560546 f22b6989 [INFO Client 23232] Tile hash: 1914648991
2024/04/11 12:15:24 5560546 f22b6988 [INFO Client 23232] Doodad hash: 0
2024/04/11 12:15:25 5561218 cff94598 [INFO Client 23232] : You have entered Enlightened Hideout.
2024/04/11 12:15:25 5561500 327589f0 [INFO Client 23232] [SHADER] Delay: ON
2024/04/11 12:15:32 5568265 cff94598 [INFO Client 23232] : EbbieTheCrow has joined the area.
2024/04/11 12:15:44 5580515 cff94598 [INFO Client 23232] : Trade accepted.
2024/04/11 12:15:47 5582765 cff94598 [INFO Client 23232] @To EbbieTheCrow: Ty!
2024/04/11 12:15:48 5584484 cff94598 [INFO Client 23232] : EbbieTheCrow has left the area.
```

SlimTrade log
[log_2024-04-11_10h45m33s.txt](https://github.com/zmilla93/SlimTrade/files/14944713/log_2024-04-11_10h45m33s.txt)

**Comment by zmilla93** [comment]
Thanks for the testing! That narrowed it down pretty quick. I'm assuming you are using the new tab feature? Tabs weren't being checked for the player joined area event.

I reuploaded the [v0.4.4-pre1 release](https://github.com/zmilla93/SlimTrade/releases/tag/v0.4.4-pre1) with the fix if you want to try it out. I'll include the fix in the next update, probably within a week or so when I have some other stuff done.

**Comment by xuvvy** [comment]
Ah, yes, I was using the new tab feature. I can also confirm that the new prerelease works and has fixed the issue. Thanks!
