### ISSUE TITLE
UI Scale option?

### ISSUE THREAD

**Issue by Tadiian** [zmilla93/SlimTrade#7]
Is it possible to add a scaling option for the UI?
On a high resolution the UI becomes somewhat small and clicking those little icons becomes a hassle, atleast for me.

**Comment by zmilla93** [comment]
I'll be adding the option for this in a future update.

I know for sure the buttons for the popup windows need to be resized, which will also carry over to the history window rows. Does text also feel too small? That has to be scaled manually. What about the popup menubar?

Anything I missed? Remaining parts of the UI will likely be left unchanged.

**Comment by Tadiian** [comment]
Late reply sorry. The Menu bar is fine, if you mean the menu that popups with "History" ect.
Text is fine too imo. Only the buttons foor replies, invites and so on could be bigger to hit them easily while in the middle of something or just too not click the wrong thing if you're going fast :)

**Comment by zmilla93** [comment]
Added in v0.2.5.

Options > General > Edit Overlay Size & Location
