### ISSUE TITLE
Overlay scale options

### ISSUE THREAD

**Issue by Jabber267** [zmilla93/SlimTrade#72]
**What feature would you like added?**
Options to scale UI elements (Options, Incoming, Outgoing etc.). 

**Why do you want this feature added?**
Things are hard to read on higher resolutions.
Also assists people with bad eyesight (like me).

**Comment by zmilla93** [comment]
Check _Options > Display > Font Size/Icon Size_. The UI will automatically rescale when these are set to higher values.

The message width can be set when editing the message overlay, and any window with a pin button can be resized and pinned to keep its new size.

If there is something that still isn't scaled well, post a full resolution screen shot so I can see the issue more clearly. I only test on 1920x1080.

**Comment by Jabber267** [comment]
Didn't realize changing font size scales the UI.
Everything looks fine on 1440p with the current scaling.
