### ISSUE TITLE
Add button to join /global 820

### ISSUE THREAD

**Issue by mr-september** [zmilla93/SlimTrade#76]
Keep getting kicked out of 820 when switching instances. This interferes with chat scanning feature.

Please add a button to join /global 820.

**Comment by zmilla93** [comment]
I'd suggest using Awakened POE Trade's chat macro feature for this. Just create a custom bind set to "/global 820". I tend to avoid repeating any features in that app because it is so widely used.

While I could add a hardcoded command to the hotkeys section, it does feel a bit niche.

**Comment by mr-september** [comment]
Oh, TIL. Thanks for the tip!
