### ISSUE TITLE
Possible to move panel from top left?

### ISSUE THREAD

**Issue by mr-september** [zmilla93/SlimTrade#77]
I can't seem to find a way to move the little 5/6-button panel from the top left, where it blocks my buff icons. 

May I ask how to do it?

**Comment by lwellers** [comment]
I options "General" you can move the toolbars.

But I can't move the grid. I don't know how to get it with a cursor. See screenshot.
<img width="287" alt="Screenshot 2024-07-29 151117" src="https://github.com/user-attachments/assets/5021734e-b364-42e9-bb94-46dfc2633004">

**Comment by mr-september** [comment]
@lwellers Thank you! Found that function under "Edit Menu & Messagebar Overlays". Then I tried the button next to it and messed up my stash tab grid too haha. Couldn't move it either, only resize.

Although now POE has built-in trade item highlighting, I haven't been using any such grid functions anymore.

**Comment by mr-september** [comment]
Just an update - looks like the "Edit Menu & Messagebar Overlays" feature does not actually save the position. Every time I close and run SlimTrade again, the Menu panel goes back to the top left of the screen.

**Comment by zmilla93** [comment]
Thanks for the reports. Working on a fix for both issues.

**Comment by zmilla93** [comment]
Fixed in v0.4.7. Restart to get the update.
