### ISSUE TITLE
Message Overlay and Stash Location not saving on application exit

### ISSUE THREAD

**Issue by fanke92** [zmilla93/SlimTrade#78]
When changing the position of the Message Overlay or the Stash Location Grid, these settings do not save when exiting and restarting SlimTrade.

Using version 0.4.6 on Windows 11.

**Comment by Unrevised9412** [comment]
Having the same issue, except that its only message and menubar. Everything else seems to save after exit.

Not sure if its relevant but logs contain this line on launch:
`2024/08/03 19:18:31 | [ERROR] [PatcherOverlay0to1] Encountered corrupted legacy save file, recreating data.`

**Comment by zmilla93** [comment]
Working on a fix, thanks for the info.

**Comment by zmilla93** [comment]
Fixed in v0.4.7. Restart to get the update.
