### ISSUE TITLE
Font is tiny and the boxes are slim

### ISSUE THREAD

**Issue by LordKnusperkrone** [zmilla93/SlimTrade#81]
Hello,

![Screenshot 2024-08-21 181451](https://github.com/user-attachments/assets/21462603-bd2c-44fe-951f-66590634a8b2)

This is my problem, i dont know how to fix it.
I updated my graphics driver and everything.

I also used the command for PowerShell, its show me nothing goes wrong.

![Screenshot 2024-08-21 182142](https://github.com/user-attachments/assets/aae9ddf5-2272-4fcf-87bf-4433c6eae31c)

Help me please :(

**Comment by zmilla93** [comment]
I'm guessing this is a font related issue. Try navigating to the display panel and adjusting the font size and style. It is the 2nd option down on the left hand side. Here is what the menu should look like for reference:

![image](https://github.com/user-attachments/assets/1d27eae4-f479-42d2-8b6c-5e836c420de3)

**Comment by zmilla93** [comment]
Closed due to lack of activity. Try the solution above.
