### ISSUE TITLE
Stash Popup not showing

### ISSUE THREAD

**Issue by aaronbeecham** [zmilla93/SlimTrade#84]
**Describe the bug**
The popup never comes up
This one, above the stash tabs:
![image](https://github.com/user-attachments/assets/ae8b72d8-2421-4f0a-a87e-7c1f6b9f3e81)

**Reproduce**
Whenever a message is sent and I open stash - it doesn't come up

**Setting** 
SlimTrade Version 0.5.8
Operation System Win11

**Comment by zmilla93** [comment]
That popup is supposed to appear when you click a button that uses "/invite {player}" on an incoming trade message (green), or when you click the item's name. If trade messages don't appear, but sure your client.txt file is set correctly in the options menu.
![image](https://github.com/user-attachments/assets/3ee92a68-c8db-46e1-a4b3-f62361672bf6)

If the item popup still doesn't appear, click "edit stash location" in the options menu, and ensure the grid is aligned to your stash.

**Comment by zmilla93** [comment]
Closed due to inactivity, and also because stash alignment has changed in 0.5.0.
