### ISSUE TITLE
Path of Exile 2 Support

### ISSUE THREAD

**Issue by zmilla93** [zmilla93/SlimTrade#86]
Coming soon. :)

Rough time estimation is 1-2 weeks after POE2's launch.

**Comment by zmilla93** [comment]
A prerelease is available for testing. It must be manually downloaded.

https://github.com/zmilla93/SlimTrade/releases

**Comment by ShinMitsuomi** [comment]
Does not work ninja price check in path of exile 2, didn't know where to post about it. https://i.imgur.com/pYyCxXB.png Or there is no support in path of exile 2 yet ?

**Comment by zmilla93** [comment]
SlimTrade 0.5.0 has been released with full Path of Exile 2 support.
