### ISSUE TITLE
From/to addition

### ISSUE THREAD

**Issue by fading-event-608** [zmilla93/SlimTrade#87]
**Describe the bug**
Since the last patch they added to/from like in poe1 to whispers which broke pretty much all buttons. I. e. when you send trade request it says "/tradewith From Name". 

**Reproduce**
Click any button that sends message, from invite to kick.

**Setting** 
0.5.0-pre5
Windows 10

**Additional context**
Kinda funny but there is a player named From. So when/if they come online every message/invite will be sent to them.

**Comment by zmilla93** [comment]
Was hoping they would fix that fairly quickly. Just released a hotfix. Thanks for reporting.
