### ISSUE TITLE
Alt Tab & Paste

### ISSUE THREAD

**Issue by aeclasik** [zmilla93/SlimTrade#9]
**What feature would you like added?**
I would like the option to click "whisper" on the trade sites which alt+tab's into POE and paste's the command automatically. Or perhaps, if there the latest clipboard message is a POE syntax'ed string then it tabs into POE and pastes it, all without me physically making POE the foreground window and manually pressing enter and pasting. #firstworldproblems

**Why do you want this feature added?**
I'm very used to this feature as the other trade helper (TraderForPoe) I was using for last few years does this already & I want to make the permanent swap to SlimTrade.

**DEV RESPONSE**
This feature exists as a hotkey. Set a hotkey in the options, copy a whisper, then press the hotkey to focus POE and send the message.
The option to instantly whisper without needing a hotkey will be added in the future. Subscribe to this issue to be alerted when it is added.

**Comment by zmilla93** [comment]
This feature exists, it just uses a hotkey. Copy a whisper, then press the hotkey to alt tab into POE and paste the message.

Some people have suggested making this completely automated. While I would like to do this, it is quite a bit more complicated and prone to error, so I used the hotkey to make sure the feature was ready for launch.

The technical reason is that Java doesn't allow you to listen for when the contents of the clipboard change directly, but instead when the DataFlavor of the clipboard changes. This means it requires a lot of extra code, and any bugs with this code may interfere with the clipboard's normal functionality.

**Comment by aeclasik** [comment]
Okay, thank you for the quick reply. Perhaps I will visit SlimTrade in the future. Really good app regardless.

**Comment by zmilla93** [comment]
I'll comment and close this issue once the new system is added so that people can subscribe to it if they want to know when the change is made. Edited the original post with a concise response.

**Comment by TheOne320** [comment]
Could it be set up like in POE-Trades-Companion, wherein you Ctrl-click the whisper button and the rest happens automatically?

**Comment by zmilla93** [comment]
Since ctrl + click is used in game to transfer items I'd need to add logic to differentiate transferring items and quick pasting trades, which would most likely relay on the clipboard listener. So in theory yes, but not until the new system is added.

**Comment by zmilla93** [comment]
Added fully automated quick pasting in v0.2.5. The option still exists to use a hotkey.
